production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: magister_app_production
  host: localhost
  username: deploy
  password: helloworld

development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: magister_app_development
  host: localhost
  username: deploy
  password: helloworld
