Course.create(name: "Didactica de la Matemática", description:'EDU0332-112', course_code: 'EDU0332-112')

User.create(first_name: 'Harold', last_name: 'Muller', email: 'hlmuller@uc.cl', role: 2, password: '123456', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'Pablo', last_name: 'Espinosa', email: 'pespinosa@uc.cl', role: 2, password: '123456', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'Vicente', last_name: 'Martin', email: 'vrmartin@uc.cl', role: 2, password: '123456', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARGARITA MARÍA', last_name: 'ALBORNOZ', email: 'mmalbornoz@uc.cl', role: 0, password: '19438227-8', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'NATALIA PAOLA', last_name: 'ALLENDES', email: 'npallendes@uc.cl', role: 0, password: '18576662-4', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARÍA IGNACIA', last_name: 'ASPILLAGA', email: 'miaspillaga@uc.cl', role: 0, password: '19243066-6', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'CECILIA VIOLETA', last_name: 'BENAVIDES', email: 'cvbenavides@uc.cl', role: 0, password: '18480236-8', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'VALERIA ISABEL', last_name: 'BRAVO', email: 'vibravo@uc.cl', role: 0, password: '18865197-6', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARIANA ISABEL', last_name: 'CILLERO', email: 'micillero@uc.cl', role: 0, password: '18391971-7', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'CATALINA SOLEDAD', last_name: 'CONTRERAS', email: 'cscontreras2@uc.cl', role: 0, password: '19245826-9', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'CONSTANZA IVONNE', last_name: 'CORNEJO', email: 'cicornejo@uc.cl', role: 0, password: '18668435-4', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'TERESITA', last_name: 'CORREA', email: 'tcorrea1@uc.cl', role: 0, password: '19247494-9', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'PAULA', last_name: 'COX', email: 'pcox1@uc.cl', role: 0, password: '19307036-1', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARGARITA MARÍA', last_name: 'DAVANZO', email: 'mmdavanzo@uc.cl', role: 0, password: '19246890-6', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'ELISA', last_name: 'DE GEYTER', email: 'edegeyter@uc.cl', role: 0, password: '19438267-7', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARIANA ANDREA', last_name: 'DÍAZ', email: 'madiaz16@uc.cl', role: 0, password: '18768772-1', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'ANTONIA ISABEL', last_name: 'ESPINOSA', email: 'aiespinosa@uc.cl', role: 0, password: '18954615-7', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARIA DEL ROSARIO', last_name: 'GARCIA', email: 'mdgarcia3@uc.cl', role: 0, password: '19606041-3', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'FLORENCIA', last_name: 'GARCÍA', email: 'fgarcia8@uc.cl', role: 0, password: '19475830-8', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'KEILA SARAI', last_name: 'GARRIDO', email: 'ksgarrido@uc.cl', role: 0, password: '13265056-K', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'ROCÍO DEL PILAR', last_name: 'GIMENO', email: 'rdgimeno@uc.cl', role: 0, password: '18955307-2', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'VALENTINA JAVIERA TERESA', last_name: 'INZUNZA', email: 'vjinzunza@uc.cl', role: 0, password: '19113339-0', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'VALENTINA IGNACIA', last_name: 'IÑÍGUEZ', email: 'viiniguez@uc.cl', role: 0, password: '19324001-1', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'VALENTINA MARÍA', last_name: 'IZQUIERDO', email: 'vmizquierdo@uc.cl', role: 0, password: '18641291-5', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'ELVIRA MARÍA ROSA', last_name: 'JARAMILLO', email: 'emjaramillo@uc.cl', role: 0, password: '19539655-8', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'COLOMBA', last_name: 'JIMÉNEZ', email: 'cjimenez2@uc.cl', role: 0, password: '19438761-K', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'ROSARIO', last_name: 'JIMÉNEZ', email: 'rjimenez1@uc.cl', role: 0, password: '19244800-K', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARÍA CATALINA', last_name: 'KREBS', email: 'mckrebs@uc.cl', role: 0, password: '19247190-7', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARÍA MAGDALENA', last_name: 'LATORRE', email: 'mmlatorre@uc.cl', role: 0, password: '19309043-5', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'TRINIDAD', last_name: 'LAVÍN', email: 'tlavin@uc.cl', role: 0, password: '19246540-0', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'FLORENCIA', last_name: 'MARAMBIO', email: 'fmarambio1@uc.cl', role: 0, password: '19350670-4', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'CAMILA ANDREA', last_name: 'MARIN', email: 'camarin2@uc.cl', role: 0, password: '19236977-0', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'NADIA CAROLINA', last_name: 'MAULEN', email: 'ncmaulen@uc.cl', role: 0, password: '18487972-7', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'PAULA ANETTE', last_name: 'MAUREIRA', email: 'pamaureira@uc.cl', role: 0, password: '19384554-1', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'ANTONIA', last_name: 'MUNITA', email: 'amunita@uc.cl', role: 0, password: '19245073-K', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'VICTORIA TRINIDAD', last_name: 'MUÑOZ', email: 'vtmunoz1@uc.cl', role: 0, password: '19606397-8', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'VANIA ANDREA', last_name: 'NAVARRO', email: 'vdnavarro@uc.cl', role: 0, password: '19522588-5', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MELANIE ALEJANDRA', last_name: 'NAVARRO', email: 'mlnavarro@uc.cl', role: 0, password: '19589316-0', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARIA FERNANDA', last_name: 'NUÑEZ', email: 'mfnunez1@uc.cl', role: 0, password: '19359389-5', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARÍA JESÚS', last_name: 'REY', email: 'mjrey@uc.cl', role: 0, password: '18396582-4', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'JAVIERA PAZ', last_name: 'SANDOVAL', email: 'jpsandoval1@uc.cl', role: 0, password: '19183414-3', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'TERESITA JESÚS', last_name: 'SILVA', email: 'tjsilva@uc.cl', role: 0, password: '19539650-7', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'ANTONIA MARÍA', last_name: 'SILVA', email: 'amsilva6@uc.cl', role: 0, password: '19322488-1', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'NICOLE ALEXANDRA', last_name: 'SMITH', email: 'nasmith@uc.cl', role: 0, password: '19438592-7', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'RAFAELA ORIANA', last_name: 'SUDY', email: 'rosudy@uc.cl', role: 0, password: '18934214-4', asistencia: false, courses: Course.where(id:1))
User.create(first_name: 'MARÍA IGNACIA', last_name: 'TORREALBA', email: 'mitorrealba@uc.cl', role: 0, password: '19567858-8', asistencia: false, courses: Course.where(id:1))


Course.create(name: "Didactica de la Lectura sección: 1", description:'EDU0330-1', course_code: 'EDU0330-1')

User.create(first_name: 'MARIA JOSE', last_name: 'ALVAREZ', email: 'mjalvarez3@uc.cl', role: 0, password: '19699842-K', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'VALENTINA DANIELA', last_name: 'ARAYA', email: 'vdaraya1@uc.cl', role: 0, password: '16606554-2', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'CONSTANZA JAVIERA', last_name: 'BAEZA', email: 'cvbaeza@uc.cl', role: 0, password: '19741392-1', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'CAMILA NATALIA', last_name: 'BRIONES', email: 'cnbriones@uc.cl', role: 0, password: '19333523-3', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'JAVIERA VALENTINA', last_name: 'BUSTOS', email: 'jvbustos@uc.cl', role: 0, password: '19331374-4', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'JAVIERA BEL�N', last_name: 'CIFUENTES', email: 'jbcifuentes@uc.cl', role: 0, password: '19377126-2', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MACARENA PAZ', last_name: 'CILLERO', email: 'mpcillero@uc.cl', role: 0, password: '19437958-7', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'JOSEFA ROSARIO', last_name: 'CISTERNAS', email: 'jrcisternas@uc.cl', role: 0, password: '19686388-5', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'CLARA MARIA', last_name: 'CORREA', email: 'cmcorrea1@uc.cl', role: 0, password: '19687467-4', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'BERNARDITA TERESA', last_name: 'CRUZ', email: 'btcruz@uc.cl', role: 0, password: '19670995-9', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'VALENTINA SOF�A', last_name: 'CUEVAS', email: 'vscuevas@uc.cl', role: 0, password: '19495450-6', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'DANIELA ALEJANDRA', last_name: 'DUR�N', email: 'djduran@uc.cl', role: 0, password: '19926620-9', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'IGNACIA MAR�A', last_name: 'ESCOBAR', email: 'imescobar@uc.cl', role: 0, password: '16153469-2', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'TERESITA DE LOS �NGELES', last_name: 'ESPINOZA', email: 'tdespinoza@uc.cl', role: 0, password: '19793371-2', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'JAVIERA FRANCISCA', last_name: 'FERRADA', email: 'jfferrada@uc.cl', role: 0, password: '18123903-4', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MARIA FERNANDA', last_name: 'FREITTE', email: 'mffreitte@uc.cl', role: 0, password: '19624691-6', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'JOSEFINA ANTONIA', last_name: 'GABLER', email: 'jagabler@uc.cl', role: 0, password: '19890981-5', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'VALENTINA ISABEL', last_name: 'GAJARDO', email: 'vigajardo@uc.cl', role: 0, password: '19689677-5', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MACARENA PAZ', last_name: 'HERRAZ', email: 'mpherraz@uc.cl', role: 0, password: '19670557-0', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'FRANCISCA', last_name: 'HURTADO', email: 'fhurtado3@uc.cl', role: 0, password: '19606681-0', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MACARENA PAULINA', last_name: 'JADUE', email: 'mpjadue@uc.cl', role: 0, password: '19526114-8', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'FRANCISCA PAULINA', last_name: 'JARA', email: 'fpjara@uc.cl', role: 0, password: '19688441-6', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MILENA CAMILA', last_name: 'MALDONADO', email: 'mcmaldonado@uc.cl', role: 0, password: '19309938-6', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MARIA JESUS', last_name: 'MANTEROLA', email: 'mjmanterola@uc.cl', role: 0, password: '19685602-1', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'DOMINIQUE PASCALE', last_name: 'M�NDEZ', email: 'damendez@uc.cl', role: 0, password: '19307813-3', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'FLORENCIA ANTONIA', last_name: 'MU�OZ', email: 'famunoz26@uc.cl', role: 0, password: '19670952-5', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'TRINIDAD CONSTANZA', last_name: 'NABZO', email: 'tcnabzo@uc.cl', role: 0, password: '19672868-6', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'RENATA JAVIERA', last_name: 'OCHOA', email: 'rjochoa@uc.cl', role: 0, password: '19671954-7', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'CATALINA ANDREA', last_name: 'OSSAND�N', email: 'caossandon@uc.cl', role: 0, password: '19408753-5', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'NATALIA MACARENA', last_name: 'PALOMINO', email: 'napalomino@uc.cl', role: 0, password: '19673038-9', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MARIA-INES', last_name: 'PONCE', email: 'mponce3@uc.cl', role: 0, password: '19636075-1', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'JAVIERA CAMILA', last_name: 'REBOLLEDO', email: 'jcrebolledo@uc.cl', role: 0, password: '18961771-2', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MARIANNE ANDREA', last_name: 'REUSE', email: 'mareuse@uc.cl', role: 0, password: '19490938-1', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'JAIR AMADOR', last_name: 'SUAREZ', email: 'jmsuarez@uc.cl', role: 0, password: '18327191-1', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'LUZ MAR�A', last_name: 'UBILLA', email: 'lmubilla@uc.cl', role: 0, password: '19669521-4', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'CATALINA ANDREA', last_name: 'VALENZUELA', email: 'cavalenzuela4@uc.cl', role: 0, password: '18935177-1', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'FLORENCIA CATALINA', last_name: 'VALENZUELA', email: 'fcvalenzuela1@uc.cl', role: 0, password: '19812582-2', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MACARENA PAZ', last_name: 'VALENZUELA', email: 'mpvalenzuela2@uc.cl', role: 0, password: '19322940-9', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'GABRIELA VIVIANA', last_name: 'V�SQUEZ', email: 'gvvasquez@uc.cl', role: 0, password: '19842667-9', asistencia: false, courses: Course.where(id:2))
User.create(first_name: 'MACARENA MARTINA', last_name: 'VIDELA', email: 'mtvidela@uc.cl', role: 0, password: '19743808-8', asistencia: false, courses: Course.where(id:2))


Course.create(name: "Didactica de la Lectura sección: 2", description:'EDU0330-2', course_code: 'EDU0330-2')

User.create(first_name: 'MACARENA JESUS', last_name: 'ALCALDE', email: 'mjalcalde@uc.cl', role: 0, password: '19694594-6', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MARIA JESUS', last_name: 'AYESTARAN', email: 'mjayestaran@uc.cl', role: 0, password: '19688993-0', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'BEATRIZ EUGENIA', last_name: 'CALVERT', email: 'becalvert@uc.cl', role: 0, password: '19687077-6', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MAGDALENA SOFIA', last_name: 'CAMELIO', email: 'mscamelio@uc.cl', role: 0, password: '19935783-2', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'IGNACIA PAZ', last_name: 'DE MARTINI', email: 'ipdemartini@uc.cl', role: 0, password: '19688130-1', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'ANDREA IGNACIA', last_name: 'D�AZ', email: 'aidiaz5@uc.cl', role: 0, password: '19135859-7', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'TANIA AURORA', last_name: 'DOM�NGUEZ', email: 'tudominguez@uc.cl', role: 0, password: '19290594-K', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'ANA MARIA', last_name: 'DONOSO', email: 'amdonoso1@uc.cl', role: 0, password: '19687740-1', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'ANTONIA', last_name: 'ECHEVERRIA', email: 'aecheverria2@uc.cl', role: 0, password: '19688363-0', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'SOFIA ANTONIA', last_name: 'ESPINOZA', email: 'snespinoza@uc.cl', role: 0, password: '19606060-K', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MARIA VALENTINA', last_name: 'FUENZALIDA', email: 'mvfuenzalida1@uc.cl', role: 0, password: '19689342-3', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'NADJA MARCELA DE LOURDE', last_name: 'GALLEGOS', email: 'nmgallegos@uc.cl', role: 0, password: '10559632-4', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MOIRA ELISA', last_name: 'GILDEMEISTER', email: 'megildemeister@uc.cl', role: 0, password: '19636280-0', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'CATALINA ANDREA', last_name: 'HERN�NDEZ', email: 'cahernandez4@uc.cl', role: 0, password: '19840674-0', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'TAMARA ALEXANDRA', last_name: 'HURTADO', email: 'tahurtado@uc.cl', role: 0, password: '19755132-1', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'ANTONIA', last_name: 'LANGLOIS', email: 'alanglois@uc.cl', role: 0, password: '19687327-9', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'JOSEFA', last_name: 'LETTICH', email: 'jlettich@uc.cl', role: 0, password: '19605316-6', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'XIMENA MARIANNA', last_name: 'MACARI', email: 'xmmacari@uc.cl', role: 0, password: '19637297-0', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MARIA JOSEFINA', last_name: 'MERY', email: 'mjmery@uc.cl', role: 0, password: '19635542-1', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'FRANCISCA', last_name: 'MOLINA', email: 'fmolina2@uc.cl', role: 0, password: '19636978-3', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'ROMINA VICTORIA', last_name: 'MORALES', email: 'rvmorales@uc.cl', role: 0, password: '16067538-1', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MACARENA MARIANELLA DE JE', last_name: 'ORELLANA', email: 'mmorellana@uc.cl', role: 0, password: '19427500-5', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MARTINA', last_name: 'PRADES', email: 'mprades@uc.cl', role: 0, password: '19637349-7', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'SOFIA', last_name: 'QUINTANA', email: 'squintana1@uc.cl', role: 0, password: '19688538-2', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MAGDALENA', last_name: 'RAMOS', email: 'mramos4@uc.cl', role: 0, password: '19842407-2', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'SOFIA', last_name: 'REDLICH', email: 'sredlich@uc.cl', role: 0, password: '19688649-4', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'BEL�N ALEJANDRA', last_name: 'ROBE', email: 'barobe@uc.cl', role: 0, password: '19310492-4', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'CATALINA ANDREA', last_name: 'ROJO', email: 'crojor@uc.cl', role: 0, password: '19341545-8', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MACARENA', last_name: 'RUIZ-TAGLE', email: 'mruiztagle2@uc.cl', role: 0, password: '19672013-8', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MAIA TALITHA', last_name: 'SCHMIDT', email: 'mtschmidt@uc.cl', role: 0, password: '19246805-1', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'VERONICA PAZ', last_name: 'SOTO', email: 'vpsoto2@uc.cl', role: 0, password: '19740827-8', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MARIA JOSE', last_name: 'UGARTE', email: 'mjugarte1@uc.cl', role: 0, password: '19636236-3', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'JOSEFINA', last_name: 'VILLARINO', email: 'jvillarino@uc.cl', role: 0, password: '19636781-0', asistencia: false, courses: Course.where(id:3))
User.create(first_name: 'MARIA LUISA', last_name: 'VILLASECA', email: 'mlvillaseca@uc.cl', role: 0, password: '18022061-5', asistencia: false, courses: Course.where(id:3))


Course.create(name: "Didactica de la Lectura sección: 3", description:'EDU0330-3', course_code: 'EDU0330-3')

User.create(first_name: 'CATALINA ANTONIA', last_name: 'ABARCA', email: 'coabarca@uc.cl', role: 0, password: '19889677-2', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'MARIA JESUS', last_name: 'AGUIRRE', email: 'msaguirre@uc.cl', role: 0, password: '19696822-9', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'MARIA LUISA', last_name: 'ALLENDE', email: 'mlallende@uc.cl', role: 0, password: '19636202-9', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'IVANA ANDREA', last_name: 'BEZMALINOVIC', email: 'iabezmalinovic@uc.cl', role: 0, password: '19813572-0', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'BELEN ELISA', last_name: 'CABELLO', email: 'becabello@uc.cl', role: 0, password: '19718409-4', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'CATALINA ALEJANDRA', last_name: 'CABRERA', email: 'cjcabrera@uc.cl', role: 0, password: '19670266-0', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'PABLO JESUS', last_name: 'CATIPILLAN', email: 'pjcatipillan@uc.cl', role: 0, password: '19518946-3', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'ARANTZA', last_name: 'CERECEDA', email: 'acereceda1@uc.cl', role: 0, password: '19406532-9', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'JOSEFA JES�S', last_name: 'C�SPEDES', email: 'jjcespedes@uc.cl', role: 0, password: '18806630-5', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'CATALINA', last_name: 'CHAIGNEAU', email: 'cchaigneau@uc.cl', role: 0, password: '19669858-2', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'GRACE CONNY', last_name: 'COLLAO', email: 'gccollao@uc.cl', role: 0, password: '17455839-6', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'MARIANA ISIDORA', last_name: 'CONCHA', email: 'miconcha5@uc.cl', role: 0, password: '19889337-4', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'TRINIDAD DE LOS MILAGROS', last_name: 'CONCHA', email: 'tdconcha@uc.cl', role: 0, password: '19606709-4', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'ALICIA', last_name: 'DE TEZANOS PINTO', email: 'adetezanospinto@uc.cl', role: 0, password: '19889378-1', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'HELBERT WLADIMIR', last_name: 'DONOSO', email: 'hwdonoso@uc.cl', role: 0, password: '18941494-3', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'KATHERINE ', last_name: 'ESCAFF', email: 'kmescaff@uc.cl', role: 0, password: '19006238-4', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'JAVIERA PAZ', last_name: 'ESCALONA', email: 'jpescalona@uc.cl', role: 0, password: '19686470-9', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'ISIDORA', last_name: 'FERNANDEZ', email: 'ifernandez2@uc.cl', role: 0, password: '19637377-2', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'RICARDO ALBERTO', last_name: 'FERRADA', email: 'raferrada@uc.cl', role: 0, password: '17286046-K', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'MARIA DE LOS ANGELES', last_name: 'FUENTES', email: 'mdfuentes3@uc.cl', role: 0, password: '19686981-6', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'JACINTA', last_name: 'GARNHAM', email: 'jgarnham1@uc.cl', role: 0, password: '19687355-4', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'CATALINA JAVIERA', last_name: 'GOMEZ', email: 'cjgomez6@uc.cl', role: 0, password: '18799504-3', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'VALENTINA FRANCISCA', last_name: 'GONZ�LEZ', email: 'vfgonzalez1@uc.cl', role: 0, password: '19521910-9', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'SOF�A ANDREA', last_name: 'GONZ�LEZ', email: 'sagonzalez1@uc.cl', role: 0, password: '19358894-8', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'CAROLINA ANDREA', last_name: 'HAHN', email: 'cnhahn@uc.cl', role: 0, password: '14555797-6', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'MAR�A LAURA SOLEDAD', last_name: 'LITTLE', email: 'mllittle@uc.cl', role: 0, password: '19522718-7', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'VALERIA JOHANA', last_name: 'MANSILLA', email: 'vjmansilla@uc.cl', role: 0, password: '19424356-1', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'JOSEFINA LORETO', last_name: 'MORALES', email: 'jlmorales@uc.cl', role: 0, password: '19400961-5', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'MACARENA ALEJANDRA', last_name: 'MU�OZ', email: 'mamunoz26@uc.cl', role: 0, password: '19163501-9', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'MARGARITA', last_name: 'OBERHAUSER', email: 'moberhauser1@uc.cl', role: 0, password: '19688976-0', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'ANDREA PAZ', last_name: 'ORELLANA', email: 'aporellana@uc.cl', role: 0, password: '19957468-K', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'BERNARDITA', last_name: 'OVALLE', email: 'bovalle1@uc.cl', role: 0, password: '19644225-1', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'CECILIA CAROLINA', last_name: 'PIMENTEL', email: 'ccpimentel@uc.cl', role: 0, password: '19423034-6', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'SEBASTI�N IGNACIO', last_name: 'PINEDA', email: 'sipineda@uc.cl', role: 0, password: '19045676-5', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'ALEJANDRA ESTEFANIA', last_name: 'POBLETE', email: 'aspoblete@uc.cl', role: 0, password: '17810794-1', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'GERALDINE LISSETTE', last_name: 'ROJAS', email: 'glrojas1@uc.cl', role: 0, password: '18934070-2', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'EMILIA ANDREA', last_name: 'ROSALES', email: 'earosales@uc.cl', role: 0, password: '18983584-1', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'CATALINA BELEN', last_name: 'SAN MARTIN', email: 'cbsanmartin@uc.cl', role: 0, password: '19817084-4', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'TAMARA ANGELINA', last_name: 'SANCHEZ', email: 'tnsanchez@uc.cl', role: 0, password: '18248105-K', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'CATALINA ISIDORA', last_name: 'TOLEDO', email: 'citoledo@uc.cl', role: 0, password: '19757447-K', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'CATALINA IN�S', last_name: 'VARGAS', email: 'civargas3@uc.cl', role: 0, password: '19524263-1', asistencia: false, courses: Course.where(id:4))
User.create(first_name: 'ANTONIA', last_name: 'VIAL', email: 'avial6@uc.cl', role: 0, password: '19605713-7', asistencia: false, courses: Course.where(id:4))
